# Generated by Django 4.2.1 on 2023-06-13 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=70)),
                ('Course_Fees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Std_Name', models.CharField(max_length=100)),
                ('Std_Address', models.CharField(max_length=200)),
                ('Std_Age', models.IntegerField()),
                ('Join_Date', models.DateField(auto_now_add=True)),
                ('Course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.coursemodel')),
            ],
        ),
    ]
