# Generated by Django 4.2.1 on 2023-06-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0003_rename_user_teachermodel_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='gender',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='Std_Address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='Std_Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='Std_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
